### ISSUE TITLE
If a CRD is deleted, stop it's watcher

### ISSUE THREAD

**Issue by bryanl** [vmware/octant#117]
When a CRD is deleted, the following is printed to the stderr

```
E0807 07:41:24.186729   16120 reflector.go:125] k8s.io/client-go/dynamic/dynamicinformer/informer.go:90: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**Comment by wwitzel3** [comment]
Right now in dynamic_cache.go, currentInformer we create all of the informers using the `dc.stopCh`. To enable this behavior octant will need to create and store a stop channel for each informer created for a given GVR.

Octant can then lookup the stop channel of an informer for a given GVR and then send the singnal to the stop channel.

**Comment by bryanl** [comment]
This is more complex than I originally thought: https://github.com/kubernetes/kubernetes/issues/79610

The solution is going to have to work around this inability to remove event handlers from informers.

**Comment by tedyu** [comment]
```
type SharedInformer interface {
```
It seems we can add a Stop func to the above interface where the stop channel is closed.
