### ISSUE TITLE
Add loading indicator (or spinner) while loading resources

### ISSUE THREAD

**Issue by alexbrand** [vmware/octant#119]
When loading resources from the backend, the UI shows an empty list/table. This could be confusing as it is not clear whether Octant is loading the list of resources or if there are indeed no resources in the cluster.

Screen capture:

![octant-loading](https://user-images.githubusercontent.com/545723/62626633-cf8af700-b8f5-11e9-8954-02706bf7687e.gif)

**Comment by wwitzel3** [comment]
I think having the default data icon be a spinner until the first response / stream from octant to the UI happens is a good idea. As you mention, this would at least signal that there are no resources of that type.

**Comment by bryanl** [comment]
There are multiple locations that should have spinners:

* in navigation
* described resources (i.e the lists you see in the dashboard)

I want to investigate solving them both. More details as I have them

**Comment by wwitzel3** [comment]
This enhancement will be in our next release.

**Comment by MarcusNoble** [comment]
It looks like this may have been removed / broken in the 0.7.0 release.
