### ISSUE TITLE
switching clusters causes crash

### ISSUE THREAD

**Issue by jipperinbham** [vmware/octant#130]
```
$ ./octant version
Version:  0.5.1
Git commit:  e0397d2596a7575abf4ca9aeacafd92912d484e0
Built:  2019-08-06T19:40:35Z
```

When I use the cluster drop-down to switch clusters, it causes octant to go into an error loop when trying to retrieve the REST mapping for the new cluster because the CRD that was in the original cluster doesn't exist in the newly selected cluster.

**Comment by bryanl** [comment]
Hi. I was able to duplicate this. We will be working on a change that will be in our next release.
