### ISSUE TITLE
Doesn't appear to support multiple kubeconfig files

### ISSUE THREAD

**Issue by mikebryant** [vmware/octant#147]
We use multiple kubeconfig files, by setting the environment variable `KUBECONFIG`

e.g. `KUBECONFIG=/home/m/.kube/config:/home/m/shared/kubeconfig`

octant should honour this and merge the files together, using the same semantics as kubectl does

**Comment by bryanl** [comment]
This is something that was considered before. I'm not sure when this will be prioritized, but you can flatten your configs for use with Octant by running 

```sh
$ env KUBECONFIG=/Users/bryan/.kube/kind-config-crd1:/Users/bryan/.kube/kind-config-crd2  kubectl config view --flatten > ~/.kube/merged
$ set -GX KUBECONFIG ~/.kube/merged
```

(i use fish, but translating this to bash or zsh shouldn't be difficult. Would calling this out in the readme help in the short term?

**Comment by bryanl** [comment]
Actually, after taking a look at the source, this feature doesn't look hard to implement. We can get it in the next release.

**Comment by mikebryant** [comment]
Wow, quick response. Thanks for the heads up, I'll hack a merged one together for now. :)

**Comment by wwitzel3** [comment]
Support for this has been merged to master and will be in the next binary release (est. Aug 20th)

**Comment by dalvizu** [comment]
Any update on this? I can confirm this is not working in the latest version in homebrew:
``
 octant version                                        
Version:  0.9.1
Git commit:  7c4bd4a03489aebba979a09aeda0c4c390650e94
Built:  2019-11-08T19:05:22Z
```
