### ISSUE TITLE
Verbosity count isn't working as expected

### ISSUE THREAD

**Issue by soggiest** [vmware/octant#149]
I'm seeing the following behavior from the Release v0.5.1 binary:
```
./octant --verbosity 2                                                       
Error: unknown command "2" for "octant"
Run 'octant --help' for usage.
unknown command "2" for "octant"
```

**Comment by petermbenjamin** [comment]
The flag is defined as [`CountVarP`](https://github.com/vmware/octant/blob/7a9bf4545f1aa288932b521f8f73830224d3f53c/internal/commands/dash.go#L110) and this is being handled by `github.com/spf13/cobra` (more specifically `github.com/spf13/pflag` in cobra).

So, the following will work:
- shorthand: `./octant -vv`
- longhand: `./octant --verbosity=2`

I'll submit a PR to improve the help output to show supported formats.

**Comment by bryanl** [comment]
We should document this. It is not obvious.
