### ISSUE TITLE
Octant loading forever if not accessed from localhost (OCTANT_LISTENER_ADDR)

### ISSUE THREAD

**Issue by Nodraak** [vmware/octant#152]
I wanted to run octant on my Kubernetes cluster and access the web ui from my dev laptop.

I set `export OCTANT_LISTENER_ADDR="0.0.0.0:8000"`, run `octant` (output looks fine) and open my browser at `http://$my_cluster_ip:8000`.

Octant starts loading html and css, but does not show any data. It appears to be due to the URL `/api/v1/content/overview/namespace/default/` returning a 403 Forbiden.

Note that it works fine if accessed from localhost: from my dev laptop `http://127.0.0.1:8000` with ssh forward `ssh -L 8000:127.0.0.1:8000 $my_cluster_ip`.

**Comment by doracl** [comment]
+1

**Comment by PsychoSid** [comment]
I am still hitting this with v0.6.0 :(

**Comment by willianccs** [comment]
> I am still hitting this with v0.6.0 :(

Same here.

**Comment by wwitzel3** [comment]
Have you tried setting `OCTANT_ACCEPTED_HOSTS` to what ever the request host IP address is? This environment variable was added in 0.6

**Comment by PsychoSid** [comment]
Ah. That works now. My bad. Sorry. Great work !

**Comment by wwitzel3** [comment]
I opened a new issue related to this, if you start Octant listening on 0.0.0.0 is should allow all hosts. See #199

**Comment by willianccs** [comment]
> `OCTANT_ACCEPTED_HOSTS`

Thanks!

**Comment by raydeo-cicd** [comment]
Same issue when running on headless linux.

OCTANT_ACCEPTED_HOSTS

Where is the env located please?
