### ISSUE TITLE
pod logs: can't scroll up after scrolling to bottom

### ISSUE THREAD

**Issue by skriss** [vmware/octant#162]
When viewing pod logs, if I scroll all the way to the bottom of the logs, the UI doesn't then let me scroll back up towards the top. If I only scroll partially down, I can scroll back up just fine.

I'm on macOS mojave and using chrome.

**Comment by wwitzel3** [comment]
I wasn't able to replicate this with FF or Chrome under Ubuntu are you able to create a gif of the problem? Also would you mind checking the browser console for any errors and pasting those as well? Thank you.

**Comment by skriss** [comment]
Seems like it only occurs if I first navigate to "Resource Viewer" for a pod, then to logs after that. I'll get a gif recorded

**Comment by wwitzel3** [comment]
@nfarruggiagl can you take a look at this and see if you can replicate and fix?

**Comment by nfarruggiagl** [comment]
Sure @wwitzel3 I will take a look!

**Comment by wwitzel3** [comment]
Fixed #189
