### ISSUE TITLE
Improve namespace selection UX on clusters with a large number of namespaces

### ISSUE THREAD

**Issue by alexbrand** [vmware/octant#168]
Currently, a user can select the active namespace via a drop-down menu. In clusters with a large number of namespaces, it can be difficult to find the desired namespace in the list.

This issue is for improving that user experience. Perhaps exposing a way for the user to type the namespace in the drop-down.

**Comment by wwitzel3** [comment]
The namespace drop down in Octant already allows you to type to filter the namespaces listed.
![octant-namespace-filter](https://user-images.githubusercontent.com/27317/63056655-7fdc9a80-beb6-11e9-94ba-bd7c4ffe6c78.gif)

**Comment by alexbrand** [comment]
Ah! I was watching someone else using Octant so it is totally possible that I missed the fact that you can type there. I think we can close this then. Thanks!
