### ISSUE TITLE
octant hangs on remote, headless Linux servers

### ISSUE THREAD

**Issue by petermbenjamin** [vmware/octant#174]
When I run octact on a remote, headless server, octant hangs in the browser.

![GIF](https://user-images.githubusercontent.com/6811830/63150120-d6cb9800-bfba-11e9-998d-65a7d7d3d5c2.gif)

octant is launched with: `$ OCTANT_LISTENER_ADDR=0.0.0.0:8900 octant -vvv`

octant logs only show DEBUG and INFO, no ERROR or WARN (other than the expected `unable to open browser` because `xdg-open` is not found).

[Logs](https://gist.github.com/petermbenjamin/a35f33ee242f2f721fc86c81254d2b58)

I've tried with a single-node `kind` cluster as well as a multi-node `kind` cluster locally and on the remote server. Octant works fine locally.

**Comment by wwitzel3** [comment]
You can add the `OCTANT_DISABLE_OPEN_BROWSER=1` flag to prevent the xdg-open error.

Also I believe this might be related to #152 (fixed in master). Our next release is ~ August 20th and will have that fix in it.
