### ISSUE TITLE
Plugin Capabilities are empty for example plugin

### ISSUE THREAD

**Issue by n3wscott** [vmware/octant#180]
The example plugin looks like it should have capabilities:

```go
	capabilities := &plugin.Capabilities{
		SupportsPrinterConfig: []schema.GroupVersionKind{podGVK},
		SupportsTab:           []schema.GroupVersionKind{podGVK},
		IsModule:              true,
	}
```

But the `Capabilities` column on the `#/content/configuration/plugins?` page is empty.

Is this expected?

**Comment by wwitzel3** [comment]
Thank you for reporting this. This is a known missing feature from our plugin system that we plan to add in a later release.

**Comment by wwitzel3** [comment]
This is now fixed in master and will be in the next release.
