### ISSUE TITLE
Extra Pod Details page is only viewable for 5 seconds.

### ISSUE THREAD

**Issue by n3wscott** [vmware/octant#181]
To Repo:

1. Install the example plugin
1. navigate to the pod details page for a pod
1. click on `Extra Pod Details` 
    - and the page is only visible for 5 seconds until the UI moves back to `Summary`

**Comment by n3wscott** [comment]
@GuessWhoSamFoo was it fixed? which version should I use now?

**Comment by wwitzel3** [comment]
This is fixed in master and will be in our next release, 0.7 which will happen very soon.
