### ISSUE TITLE
Update store to return if object is found in a Get request

### ISSUE THREAD

**Issue by bryanl** [vmware/octant#184]
`Get` signature is currently `Get(...) (*unstructured.Unstructured, error)`. There may 
be an issue with the get request and there are multiple classes of errors. When an object
is not found, it should be obvious to the caller. I'm proposing that we change `Get` to
`Get(...) (object *unstructured.Unstructured, found bool, err error)`. With this change
the caller doesn't have to know anything about the implementation of `Get`. Also, this
means Get can guarantee a non nil object if `found == true && err == nil`.

**Comment by wwitzel3** [comment]
Added with #211
