### ISSUE TITLE
Proposal: create a well defined port for the octant API

### ISSUE THREAD

**Issue by bryanl** [vmware/octant#185]
Problem:

Octant starts its API on a random port on 127.0.0.1. This avoids potential conflicts. Giving Octant a well defined port number by default means that you could know what the port number is and restarts of the application wouldn't require the browser URL to change. I'm going to suggest two numbers for default ports: 

* 102016 - date Heptio was founded
* 7777 - Kubernetes people seem to like 7s

**Comment by GuessWhoSamFoo** [comment]
+1 for 7777 - easy to remember

**Comment by wwitzel3** [comment]
I like 8888 or 8088 only because octagon / eight theme

**Comment by wwitzel3** [comment]
I changed my mind, I actually like `7777` the best.

**Comment by buddiex** [comment]
there should be an option to change this. a `--port` cli option. I have an issue where an k8 `7777` service is forward and now can run octant.
