### ISSUE TITLE
Navigation generation can fail when custom resources can't be listed 

### ISSUE THREAD

**Issue by bryanl** [vmware/octant#195]
It should be able to generate overview and cluster overview navigation even when the user can't list custom resources. Currently, it will fail and you will get no menus.

**Comment by willianccs** [comment]
Also is it possible to generate overview only with "list" permissions instead of "get" on cluster objects?

**Comment by wwitzel3** [comment]
Yes, that may be possible, we do actually check for list vs. get permissions when fetching resources, I think likely we have some nested calling that results in an error for list if a get call fails. We can look in to a better way to isolate these.

I do wonder what the user experience would be like to view a list of objects that you get a permission denied on when attempting to view them. That should be considered here as well.

**Comment by moderation** [comment]
Confirming that the left menu / column is now displaying after building from master and running against a cluster with high restriction levels including listing CRDs. Thanks.

**Comment by wwitzel3** [comment]
Thank you for confirming. This current fix will add some more noise to the console (the warnings output for the access failure), but we have some changes coming in 0.8 (0.7 is releasing early next week) that will clean all of that up.
