### ISSUE TITLE
Namespace Dropdown Not Refreshed When Changing Cluster Context

### ISSUE THREAD

**Issue by PsychoSid** [vmware/octant#206]
When running on a GKE environment with multiple clusters a single account that has all clusters available as contexts displays all the clusters in the context list fine.

However when switching to a new cluster/context the namespace list is not refreshed.

You can alter the URL manually and the resources do show but a message "The current set namespace is not valid" is displayed at the top of the screen.

If I leave a common namespace selected "default|kube-system" etc then the details such as "Services" update to the required context on the next poll.

Thanks.

**Comment by pdemagny** [comment]
I'm experiencing the very same issue with 3 EKS clusters. It only works using the url trick as stated by @PsychoSid :(
I would add that the box to switch clusters is too short for standard EKS cluster names like `arn:aws:eks:eu-west-1:133713371337:cluster/mycluster`.

**Comment by bryanl** [comment]
We're aware of this and are currently re-engineering the process that generates it to make it 1) easier to update 2) actually update. There will be a fix for this in in 0.7 later this month.

**Comment by bryanl** [comment]
This should be fixed when #239 is merged. Revamped the whole process.

**Comment by wwitzel3** [comment]
Fixed in master and will be available in the next release.
