### ISSUE TITLE
No content displayed when setting OCTANT_LISTENER_ADDR=0.0.0.0:7777

### ISSUE THREAD

**Issue by ylvmw** [vmware/octant#237]
Steps:
1. Start octant with the command: OCTANT_DISABLE_OPEN_BROWSER=1 OCTANT_LISTENER_ADDR=0.0.0.0:7777 ./octant
2. Access it from the remote web  browser: http://<octant_host>:7777
3. Check the content

Expected:
Cluster contents could be displayed correctly

Actual:
On content displayed except the header.

**Comment by wanghaiqing2015** [comment]
OCTANT_ACCEPTED_HOSTS=10.45.112.17 KUBECONFIG=/root/.kube/config OCTANT_LISTENER_ADDR=0.0.0.0:8900 octant

**Comment by wwitzel3** [comment]
Hi @ylvmw we are aware of this current behavior. We have a fix merged in to master (https://github.com/vmware/octant/pull/200) that will be in the next release.

In the meantime, as @wanghaiqing2015 pointed out, you can explicitly set `OCTANT_ACCEPTED_HOSTS`

**Comment by ylvmw** [comment]
Thanks @wwitzel3. Setting OCTANT_ACCEPTED_HOSTS didn't work for me. 
When would the next release probably be published?

**Comment by wwitzel3** [comment]
Next release is scheduled for next Monday, Sept 09.

**Comment by ylvmw** [comment]
Great! Thanks.

**Comment by binaryWorld** [comment]
> Next release is scheduled for next Monday, Sept 09.

https://github.com/vmware/octant/releases   latest version ：0.6

When would the next release probably be published?

**Comment by wwitzel3** [comment]
You can expect to see it late this week or early next. We have a couple PRs in flight that are larger that we want to get in to the 0.7 release.
