### ISSUE TITLE
Link to objects in another cluster

### ISSUE THREAD

**Issue by zoidbergwill** [vmware/octant#280]
There are a few tools out there that manage deploying workloads to multiple clusters, like [shipper](https://github.com/bookingcom/shipper), [rancher](https://rancher.com/products/rancher/multi-cluster-management/), and [admiralty](https://admiralty.io/).

I was thinking of writing a plugin for Shipper, to provide better visibility between clusters, but I'm not sure how I'd do linking between contexts/clusters.

Not sure if you folks had any ideas about this problem? I was thinking maybe people had thought about doing a similar thing for [gimbal](https://github.com/heptio/gimbal)

**Comment by wwitzel3** [comment]
We currently do not have a way to query objects across cluster right now. We do want to expose this eventually and we know it is something that will be useful to plug-in authors.

**Comment by wwitzel3** [comment]
After some further investigation, Octant will only connect to a single cluster at a time. Your plugin can still show visibility in to the deployments, but the user of Octant will need to use the context switcher to cycle through clusters.
