### ISSUE TITLE
Problem adding an external link to SummarySection

### ISSUE THREAD

**Issue by garethr** [vmware/octant#315]
I'd like to add a link to an external site into a row on the status panel.

Trying to use `NewLink`:

```go
{Header: "Title", Content: component.NewLink("", "Example", "https://example.com")}
```

Results in a relative link, not an absolute one, like so: http://127.0.0.1:7777/#/content/overview/namespace/default/workloads/deployments/<name>/https://example.com

Trying to use `NewMarkdownText` instead:

```go
{Header: "Title", Content: component.NewMarkdownText("[Example](https://example.com)")}
```

The absolute link works here, but results in wrapping the link in a paragraph, which adds lots of additional padding to the top of the text when rendered in the table.

It would be nice to have a way of adding nicely formatted external links to a panel, by fixing either of the above behaviours or by adding a new `NewExternalLink`.

**Comment by wwitzel3** [comment]
This is fixed in master now.
