### ISSUE TITLE
Initial load is too slow

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#41]
@bryanl commented on [Mon May 27 2019](https://github.com/heptio/developer-dash/issues/799)

Initial load time is too slow. In the browser it can take upwards of 30 seconds to display the dashboard.

---

@wwitzel3 commented on [Wed Jun 05 2019](https://github.com/heptio/developer-dash/issues/799#issuecomment-499207813)

thought, decouple the loading of the initial objects from the generation of the connection graph

**Comment by wwitzel3** [comment]
Investigate performing the initial load using direct client calls and then switching subsequent calls over to using the informer backed store.

**Comment by wwitzel3** [comment]
@bryanl I think #51 has solved this in the original spirit of this issue and we should open more specific performance issues as needed.

**Comment by bryanl** [comment]
@wwitzel3 true. closing this issue
