### ISSUE TITLE
Document contributing to the UI

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#48]
@mdaverde commented on [Mon May 13 2019](https://github.com/heptio/developer-dash/issues/782)

This can be part of overall contribution doc, but I wanted an issue to capture UI specifics. We should mention:

- Getting set up
- Overview of design
- Testing requirements of changes/new features

**Comment by mdaverde** [comment]
This issue can be closed unless we feel something is missing from this [README](https://github.com/vmware/octant/tree/master/web).

We should consider linking to this from the main README.
