### ISSUE TITLE
Handle invalid kubeconfig files

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#57]
@bryanl commented on [Wed Nov 21 2018](https://github.com/heptio/developer-dash/issues/252)

Handling invalid kubeconfig files:

* don't panic/exit on invalid kubeconfig files
* ensure log message generated includes the fact that there is an issue with the kubeconfig file
* send invalid kubeconfig status to frontend

**Comment by bryanl** [comment]
With #164, octant now uses client-go's code paths for handling kubeconfig files. So this means that octant would do the same thing kubectl would do ie. error?

**Comment by wwitzel3** [comment]
Closing. That is the correct behavior when getting an invalid kubeconfig.
