### ISSUE TITLE
Create set of resource YAML that can be used for testing

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#69]
@bryanl commented on [Wed Oct 03 2018](https://github.com/heptio/developer-dash/issues/42)

- [x] Cron job
- [x] daemon set
- [x] deployment
- [x] Job
- [x] Replica set
- [x] Replication controller
- [x] Stateful set
- [x] Ingress
- [x] Service
- [x] Config map
- [x] PVC
- [x] Secret
- [x] Role
- [x] Role binding
- [ ] Event?

**Comment by wsandin** [comment]
I can help with this, if still needed.

**Comment by bryanl** [comment]
@wsandin Sure! This would be very helpful

**Comment by wsandin** [comment]
So if I understand correctly, we still need (Ingress|ConfigMap|Secret|Role|Role Binding|Event) and not the already ticked ones. Can you assign me this issue?

**Comment by wwitzel3** [comment]
@wsandin yeah the already checked ones we have example YAML for, but it may be good to give them a review while we are adding the new ones.

**Comment by wwitzel3** [comment]
hey @wsandin wanted to check-in and see where you were at with this?

**Comment by phenixblue** [comment]
Happy to help with this as well if needed

**Comment by phenixblue** [comment]
Looks like all of the objects listed have been covered now. Is there anything else needed?
