### ISSUE TITLE
Switching Namespace

### ISSUE THREAD

**Issue by rbankston** [vmware/octant#73]
## Feature Request

Didn't see this listed anywhere and probably a nit on my part.  When switching namespaces while looking at a specific resource I would expect to stay on that resource but change the namespace or have the option to configure that somewhere. 

## What Happened

With octant running and accessing [Service Accounts in the default namespace](http://127.0.0.1:51314/#/content/overview/namespace/default/config-and-storage/service-accounts?) changed namespaces to  kube-system and was brought to the [kube-system namespace overview](http://127.0.0.1:51314/#/content/overview/namespace/kube-system?)

## What I expected

With octant running and accessing [Service Accounts in the default namespace](http://127.0.0.1:51314/#/content/overview/namespace/default/config-and-storage/service-accounts?) change namespaces to kube-system and be brought to [Service Accounts in the kube-system namespace](http://127.0.0.1:51314/#/content/overview/namespace/kube-system/config-and-storage/service-accounts?)

**Comment by bryanl** [comment]
@rbankston #80 has been merged to handle this. The behavior is now as you describe.
