### ISSUE TITLE
Add homebrew install

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware/octant#75]
Xref: https://github.com/Homebrew/homebrew-core/pull/42319

- [x] 30 watches
- [x] 30 forks
- [x] 75 stars
- [x] Update readme

**Comment by dideler** [comment]
More than 30 watchers now ;)

**Comment by GuessWhoSamFoo** [comment]
Trying this again: https://github.com/Homebrew/homebrew-core/pull/43332
