### ISSUE TITLE
Linking to unsupported objects

### ISSUE THREAD

**Issue by bryanl** [vmware/octant#86]
There is a cohort of objects that Octant doesn't support (e.g. `apps/v1 ControllerRevision`). If they show up in the resource viewer, there is no way to link to them since there is no dashboard view for them. There needs to be a way to handle this case. There are a few options in this case. 

1. Add these objects to the dashboard. Then they can be linked. The issue here is they might not be useful on their own. DaemonSet and ReplicaSet use ControllerRevision internally.
2. Don't visit these objects. 

/cc @wwitzel3

**Comment by wwitzel3** [comment]
`apps/v1 ControllerRevision` is an example of an object that doesn't really provide a lot of useful information with respect to the resourceviewer view. The information from that object seems more appropriate for a status / detail view.

**Comment by bryanl** [comment]
I propose we don't visit these. The object visitor could be updated to never visit these objects.

**Comment by wwitzel3** [comment]
@bryanl and I chatted about this and we are going to create a GVK allowed list as an initial step.
